#pragma once

// Phase 5 interface source. The generated gzip header is what the ESP32 serves.
// No API credential or third-party asset is embedded in this page.
const char PHASE3_INDEX_HTML[] PROGMEM = R"HTML(
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#f5f3ee">
  <title>Solar inspection</title>
  <style>
    :root{color-scheme:light;--canvas:#f5f3ee;--surface:#fffdfa;--ink:#292c32;--muted:#74747b;
      --line:#dedad2;--strong:#cbc5bb;--blue:#557fc4;--blue2:#3e68ac;--blue-soft:#e5eef9;
      --sage:#dfece2;--sage-ink:#35604a;--peach:#f6e3d7;--peach-ink:#945837;
      --lilac:#eee9f6;--lilac-ink:#665486;--rose:#f6e4e6;--rose-ink:#984852;
      --amber:#d58b35;--red:#c5535f;--shadow:0 1px 2px #302b2308,0 12px 34px #302b230a;
      font-family:"Avenir Next","SF Pro Text","Segoe UI",system-ui,-apple-system,sans-serif;font-synthesis:none}
    *{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;background:var(--canvas);color:var(--ink);font-size:15px;line-height:1.45}
    button,input{font:inherit}.topbar{min-height:54px;border-bottom:1px solid var(--line);background:#fffdfacc;
      backdrop-filter:blur(12px);display:flex;align-items:center;justify-content:space-between;gap:18px;padding:10px 28px;position:sticky;top:0;z-index:20}
    .identity,.telemetry,.actions,.switch-row{display:flex;align-items:center}.identity{gap:12px}.product{font-weight:680;letter-spacing:-.01em}.telemetry{gap:20px;color:var(--muted);font-size:13px}
    .status{display:inline-flex;align-items:center;min-height:27px;padding:4px 10px;border-radius:7px;background:var(--blue-soft);color:#48617f;font-size:12px;font-weight:680;white-space:nowrap}
    .status.good{background:var(--sage);color:var(--sage-ink)}.status.warn{background:var(--peach);color:var(--peach-ink)}.status.bad{background:var(--rose);color:var(--rose-ink)}
    .shell{width:min(1420px,100%);margin:auto;padding:24px 28px 16px}.intro{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:18px}
    h1{margin:0;font-size:clamp(30px,3.2vw,44px);line-height:1.04;letter-spacing:-.04em;font-weight:660}.subtitle{margin:7px 0 0;color:var(--muted);font-size:16px}.privacy{max-width:340px;margin:0;text-align:right;color:var(--muted);font-size:13px}
    .workspace{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(355px,.9fr);gap:16px;align-items:start}.stack{display:grid;gap:14px}
    .panel{border:1px solid var(--line);border-radius:14px;background:var(--surface);box-shadow:var(--shadow)}.panel-body{padding:14px}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:10px}.panel-head h2{margin:0;font-size:16px;letter-spacing:-.01em}
    .media{position:relative;overflow:hidden;border-radius:10px;background:#10151a;aspect-ratio:4/3}.live-media{aspect-ratio:3/2}.media img{display:block;width:100%;height:100%;object-fit:contain}.media img:not([src]){display:none}
    .media-empty{position:absolute;inset:0;display:grid;place-items:center;padding:28px;text-align:center;color:#c4cad0;background:#10151a}.media-empty strong{display:block;color:#fff;font-size:16px;margin-bottom:5px}.capture-frame{background:#fbfaf7;border:1px dashed var(--strong)}.capture-frame .media-empty{background:#fbfaf7;color:var(--muted)}.capture-frame .media-empty strong{color:var(--ink)}
    .frame-caption{position:absolute;left:10px;right:10px;bottom:10px;display:flex;justify-content:space-between;gap:8px;color:#f6f7f8;font-size:12px;pointer-events:none}.frame-caption span{padding:5px 8px;border-radius:6px;background:#10151ad9}
    #defectOverlay{position:absolute;inset:0;width:100%;height:100%;z-index:3;pointer-events:none}.bbox{pointer-events:auto;cursor:pointer}.bbox rect{fill:rgba(213,139,53,.08);stroke:var(--amber);stroke-width:8;vector-effect:non-scaling-stroke}.bbox.high rect{fill:rgba(197,83,95,.1);stroke:var(--red)}.bbox.low rect{fill:rgba(85,127,196,.08);stroke:var(--blue)}.bbox.selected rect{stroke-width:12;filter:drop-shadow(0 2px 3px #1118)}
    .bbox .tag{fill:#1f2329;stroke:none}.bbox text{fill:white;font:650 34px "Avenir Next",sans-serif;letter-spacing:.01em}.approx{position:absolute;top:10px;left:10px;z-index:4;padding:5px 8px;border-radius:6px;background:#10151ad9;color:#fff;font-size:11px}
    .metric-row{display:grid;grid-template-columns:repeat(4,1fr);margin-top:10px;border:1px solid var(--line);border-radius:11px;background:#fbfaf7}.metric{padding:9px 14px;min-width:0}.metric+.metric{border-left:1px solid var(--line)}.metric-label{display:block;color:var(--muted);font-size:11px;margin-bottom:3px}.metric-value{font-weight:630;font-variant-numeric:tabular-nums;white-space:nowrap}
    .button{min-height:44px;border:1px solid transparent;border-radius:9px;padding:9px 14px;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;cursor:pointer;font-weight:670;transition:.16s background-color,.16s border-color,.16s transform}.button:hover:not(:disabled){transform:translateY(-1px)}.button:focus-visible,input:focus-visible{outline:3px solid #557fc447;outline-offset:2px}.button:disabled,.button[aria-disabled=true]{opacity:.5;pointer-events:none}.button.primary{width:100%;background:var(--blue);color:#fff}.button.primary:hover:not(:disabled){background:var(--blue2)}.capture-frame+.button{margin-top:12px}.button.secondary{flex:1;background:#fff;color:var(--ink);border-color:var(--strong)}.button.secondary:hover:not(:disabled){background:var(--blue-soft)}.actions{gap:9px;margin-top:10px}
    .message{min-height:21px;margin:10px 1px 0;color:var(--muted);font-size:13px}.analysis{background:#fcfafd;border-color:#ddd6e9}.analysis-body{min-height:158px;border-radius:10px;background:var(--lilac);padding:15px}.center{text-align:center}.analysis-body h3{margin:7px 0 4px;font-size:18px;letter-spacing:-.01em}.analysis-body p{margin:0;color:#675f71}.analysis-body .button{margin-top:14px;background:transparent;color:var(--lilac-ink);border-color:#ab9dc3;width:100%}
    .summary{margin:8px 0 12px!important}.result-meta{display:flex;gap:6px;flex-wrap:wrap}.defect-list{display:grid;gap:7px;margin-top:12px}.defect{width:100%;border:1px solid #d3c9e0;border-radius:9px;background:#ffffffa8;padding:9px 10px;text-align:left;color:var(--ink);cursor:pointer}.defect:hover,.defect.selected{border-color:#8f7baa;background:#fff}.defect-top{display:flex;justify-content:space-between;gap:10px;font-size:13px;font-weight:680}.defect p{margin:3px 0 0;font-size:12px}.note{margin-top:11px!important;font-size:11px!important;color:#786e82!important}
    details.settings{border-top:1px solid #d9d1e4;margin-top:13px;padding-top:10px}details summary{cursor:pointer;color:var(--lilac-ink);font-size:12px;font-weight:680}.endpoint{display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:9px}.endpoint input{min-width:0;border:1px solid #cfc5da;border-radius:8px;background:#fff;padding:9px;color:var(--ink)}.endpoint .button{min-height:40px;margin:0;width:auto;background:#fff}.hint{margin-top:6px!important;font-size:11px!important}
    .switch-row{justify-content:space-between;gap:12px;margin-top:10px;font-size:12px;color:var(--muted)}.switch-row input{accent-color:var(--blue)}
    .health{display:grid;grid-template-columns:145px repeat(6,1fr) auto;align-items:center;margin-top:14px;padding:0 18px;min-height:64px}.health-title{font-weight:680}.health-item{padding:9px 14px;border-left:1px solid var(--line)}.health-item span{display:block}.health-label{color:var(--muted);font-size:11px}.health-value{font-weight:630;font-variant-numeric:tabular-nums;white-space:nowrap}.refresh{min-height:38px;background:var(--peach);color:var(--peach-ink)}
    .footer{display:flex;justify-content:space-between;gap:20px;margin-top:9px;color:var(--muted);font-size:12px}
    @media(max-width:1080px){.workspace{grid-template-columns:1.3fr .9fr}.health{grid-template-columns:130px repeat(4,1fr) auto}.optional{display:none}}
    @media(max-width:840px){.topbar{padding:10px 16px}.telemetry .desktop{display:none}.shell{padding:22px 16px}.intro{align-items:flex-start;flex-direction:column}.privacy{text-align:left}.workspace{grid-template-columns:1fr}.stack{grid-template-columns:1fr 1fr}.health{grid-template-columns:repeat(3,1fr);padding:12px}.health-title{grid-column:1/-1;padding:3px 8px 8px}.health-item{border-left:0;padding:8px}.refresh{grid-column:1/-1;margin:6px 8px 2px}.footer{flex-direction:column;gap:3px}}
    @media(max-width:640px){body{font-size:14px}.product,.telemetry .optional-mobile{display:none}.stack{grid-template-columns:1fr}.intro{margin-bottom:16px}.privacy{display:none}.panel-body{padding:12px}.metric-row{grid-template-columns:1fr 1fr}.metric:nth-child(3){border-left:0;border-top:1px solid var(--line)}.metric:nth-child(4){border-top:1px solid var(--line)}.actions{flex-direction:column}.button.secondary{width:100%}.endpoint{grid-template-columns:1fr}.endpoint .button{width:100%}}
    @media(prefers-reduced-motion:reduce){*{transition:none!important}}
  </style>
</head>
<body>
  <header class="topbar"><div class="identity"><span id="deviceBadge" class="status">Camera connecting</span><span class="product">Solar Inspector</span></div><div class="telemetry"><span>Backend <strong id="backendTop">checking</strong></span><span class="optional-mobile">Wi-Fi <strong id="topRssi">—</strong></span><span class="desktop">FPS <strong id="topFps">—</strong></span></div></header>
  <main class="shell">
    <section class="intro"><div><h1>Visible-defect inspection</h1><p class="subtitle">Capture a detailed panel image, analyze it, and review marked regions.</p></div><p class="privacy">The API key stays on your Mac. Captures remain temporary and are not stored by this application.</p></section>
    <section class="workspace">
      <div><section class="panel panel-body"><div class="panel-head"><h2>Live view</h2><span id="streamBadge" class="status">Starting preview</span></div><div class="media live-media"><img id="stream" alt="Live preview from the ESP32 solar panel camera"><div id="streamEmpty" class="media-empty"><div><strong>Connecting to camera</strong><span>The preview will appear here.</span></div></div><div class="frame-caption"><span>QVGA · 320 × 240</span><span id="frameFps">— fps</span></div></div></section><div class="metric-row"><div class="metric"><span class="metric-label">Stream rate</span><span id="metricFps" class="metric-value">—</span></div><div class="metric"><span class="metric-label">JPEG size</span><span id="metricBytes" class="metric-value">—</span></div><div class="metric"><span class="metric-label">Browser transfer</span><span id="metricDownload" class="metric-value">—</span></div><div class="metric"><span class="metric-label">Camera capture</span><span id="metricCapture" class="metric-value">—</span></div></div></div>
      <div class="stack">
        <section class="panel panel-body"><div class="panel-head"><h2>Inspection frame</h2><span id="captureBadge" class="status good">Ready</span></div><div class="media capture-frame"><img id="still" alt="Latest high-resolution captured solar panel image"><svg id="defectOverlay" viewBox="0 0 1600 1200" role="img" aria-label="Approximate detected regions" hidden></svg><span id="approxNote" class="approx" hidden>Approximate AI regions</span><div id="captureEmpty" class="media-empty"><div><strong>No image captured yet</strong><span>Capture a fresh 1600 × 1200 inspection frame.</span></div></div><div id="captureCaption" class="frame-caption" hidden><span id="captureResolution">UXGA · 1600 × 1200</span><span id="captureClock">—</span></div></div><button id="captureButton" class="button primary" type="button">Capture image</button><div id="capturedActions" class="actions" hidden><button id="retakeButton" class="button secondary" type="button">Retake</button><a id="downloadButton" class="button secondary" href="#" download>Original JPEG</a><button id="annotatedButton" class="button secondary" type="button" hidden>Annotated JPEG</button></div><p id="captureMessage" class="message" role="status" aria-live="polite">Ready for a fresh capture.</p></section>
        <section class="panel panel-body analysis"><div class="panel-head"><h2>Analysis</h2><span id="analysisBadge" class="status">No image</span></div><div class="analysis-body" aria-live="polite"><div id="analysisEmpty" class="center"><h3 id="analysisTitle">Capture an image first</h3><p id="analysisPrompt">Analysis becomes available when a valid UXGA still is ready.</p></div><div id="analysisResult" hidden><div class="result-meta"><span id="resultStatus" class="status"></span><span id="qualityStatus" class="status"></span></div><h3 id="resultTitle">Inspection result</h3><p id="resultSummary" class="summary"></p><div id="defectList" class="defect-list"></div><p class="note">Screening aid only. Bounding boxes are approximate and results require manual review.</p></div><button id="analyzeButton" class="button" type="button" disabled>Analyze captured image</button><div class="switch-row"><label><input id="overlayToggle" type="checkbox" checked disabled> Show marked regions</label><span id="analysisTiming"></span></div><details class="settings"><summary>Backend connection</summary><div class="endpoint"><input id="backendUrl" type="url" aria-label="Mac backend URL" spellcheck="false"><button id="backendSave" class="button" type="button">Save & test</button></div><p id="backendMessage" class="hint">The API key never enters this browser.</p></details></div></section>
      </div>
    </section>
    <section class="panel health"><div class="health-title">System health</div><div class="health-item"><span class="health-label">Camera Wi-Fi</span><span id="healthRssi" class="health-value">—</span></div><div class="health-item"><span class="health-label">Camera memory</span><span id="healthHeap" class="health-value">—</span></div><div class="health-item"><span class="health-label">PSRAM</span><span id="healthPsram" class="health-value">—</span></div><div class="health-item optional"><span class="health-label">Camera IP</span><span id="healthIp" class="health-value">—</span></div><div class="health-item"><span class="health-label">Backend mode</span><span id="healthBackend" class="health-value">—</span></div><div class="health-item optional"><span class="health-label">Firmware</span><span id="healthFirmware" class="health-value">—</span></div><button id="refreshButton" class="button refresh" type="button">Refresh</button></section>
    <footer class="footer"><span>Visible-defect screening prototype · Not a certified electrical diagnosis</span><span>Phase 5 · Vision analysis with on-device status</span></footer>
  </main>
  <script>
    const $=id=>document.getElementById(id),CAPTURE_WIDTH=1600,CAPTURE_HEIGHT=1200,SVG='http://www.w3.org/2000/svg';
    const ui={stream:$('stream'),streamEmpty:$('streamEmpty'),streamBadge:$('streamBadge'),still:$('still'),captureEmpty:$('captureEmpty'),captureCaption:$('captureCaption'),captureBadge:$('captureBadge'),captureMessage:$('captureMessage'),captureButton:$('captureButton'),capturedActions:$('capturedActions'),retakeButton:$('retakeButton'),downloadButton:$('downloadButton'),annotatedButton:$('annotatedButton'),analyzeButton:$('analyzeButton'),analysisBadge:$('analysisBadge'),analysisEmpty:$('analysisEmpty'),analysisResult:$('analysisResult'),resultStatus:$('resultStatus'),qualityStatus:$('qualityStatus'),resultTitle:$('resultTitle'),resultSummary:$('resultSummary'),defectList:$('defectList'),overlay:$('defectOverlay'),overlayToggle:$('overlayToggle'),approxNote:$('approxNote'),backendUrl:$('backendUrl'),backendMessage:$('backendMessage')};
    const app={stillBlob:null,stillUrl:null,streamPaused:false,streamRetry:null,busy:false,result:null,selected:0,backend:null};
    const defaultBackend='http://ajays-macbook-pro-2.local:8000';ui.backendUrl.value=localStorage.getItem('solarBackendUrl')||defaultBackend;
    const sleep=ms=>new Promise(r=>setTimeout(r,ms)),label=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
    const setBadge=(el,text,tone='')=>{el.textContent=text;el.className=`status ${tone}`.trim()},formatBytes=n=>n?`${(n/1024).toFixed(1)} KB`:'—';
    function busy(value){app.busy=value;ui.captureButton.disabled=value;ui.retakeButton.disabled=value;ui.downloadButton.setAttribute('aria-disabled',value);ui.analyzeButton.disabled=value||!app.stillBlob}
    function streamMessage(title,detail){ui.streamEmpty.innerHTML='';const box=document.createElement('div'),strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=title;span.textContent=detail;box.append(strong,span);ui.streamEmpty.append(box);ui.streamEmpty.hidden=false}
    function startStream(){clearTimeout(app.streamRetry);app.streamPaused=false;setBadge(ui.streamBadge,'Connecting');streamMessage('Connecting to camera','The preview will appear here.');ui.stream.src=`http://${location.hostname}:81/stream?t=${Date.now()}`}
    function pauseStream(){app.streamPaused=true;clearTimeout(app.streamRetry);ui.stream.removeAttribute('src');setBadge(ui.streamBadge,'Paused for capture','warn');streamMessage('Preview paused','Preparing a high-resolution still.')}
    ui.stream.addEventListener('load',()=>{ui.streamEmpty.hidden=true;setBadge(ui.streamBadge,'Streaming','good')});ui.stream.addEventListener('error',()=>{if(app.streamPaused)return;setBadge(ui.streamBadge,'Reconnecting','bad');streamMessage('Preview interrupted','Reconnecting automatically…');app.streamRetry=setTimeout(startStream,2000)});
    function clearOverlay(){ui.overlay.replaceChildren();ui.overlay.setAttribute('hidden','');ui.approxNote.hidden=true;ui.overlayToggle.disabled=true;ui.annotatedButton.hidden=true}
    function resetAnalysis(){app.result=null;app.selected=0;clearOverlay();ui.analysisResult.hidden=true;ui.analysisEmpty.hidden=false;ui.analyzeButton.hidden=false;ui.analyzeButton.textContent='Analyze captured image';ui.analyzeButton.disabled=app.busy||!app.stillBlob;setBadge(ui.analysisBadge,app.stillBlob?'Ready':'No image',app.stillBlob?'good':'');$('analysisTitle').textContent=app.stillBlob?'Image ready':'Capture an image first';$('analysisPrompt').textContent=app.stillBlob?'Send this capture securely to the analysis service.':'Analysis becomes available when a valid UXGA still is ready.';$('analysisTiming').textContent=''}
    async function loadStill(blob){const next=URL.createObjectURL(blob),previous=app.stillUrl;ui.still.src=next;try{if(ui.still.decode)await ui.still.decode();const w=ui.still.naturalWidth,h=ui.still.naturalHeight;if(w!==CAPTURE_WIDTH||h!==CAPTURE_HEIGHT)throw new Error(`Expected ${CAPTURE_WIDTH} × ${CAPTURE_HEIGHT}, received ${w} × ${h}`);if(previous)URL.revokeObjectURL(previous);app.stillBlob=blob;app.stillUrl=next;return{width:w,height:h}}catch(e){URL.revokeObjectURL(next);if(previous)ui.still.src=previous;else ui.still.removeAttribute('src');throw e}}
    async function captureImage(){busy(true);pauseStream();resetAnalysis();setBadge(ui.captureBadge,'Capturing','warn');ui.captureMessage.textContent='Capturing a fresh 1600 × 1200 image…';const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),30000),started=performance.now();try{await sleep(250);const response=await fetch(`/capture?t=${Date.now()}`,{cache:'no-store',signal:ctrl.signal});if(!response.ok)throw new Error(`Camera returned HTTP ${response.status}`);const blob=await response.blob(),dimensions=await loadStill(blob),elapsed=Math.round(performance.now()-started);ui.captureEmpty.hidden=true;ui.captureCaption.hidden=false;ui.captureButton.hidden=true;ui.capturedActions.hidden=false;ui.downloadButton.href=app.stillUrl;ui.downloadButton.download=`solar-panel-${new Date().toISOString().replaceAll(':','-')}.jpg`;$('captureClock').textContent=new Intl.DateTimeFormat([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());$('captureResolution').textContent=`UXGA · ${dimensions.width} × ${dimensions.height}`;$('metricCapture').textContent=`${response.headers.get('X-Capture-Time-Ms')||'?'} ms`;$('metricDownload').textContent=`${elapsed} ms`;$('metricBytes').textContent=formatBytes(blob.size);setBadge(ui.captureBadge,'Captured','good');ui.captureMessage.textContent=`Fresh image received in ${elapsed} ms.`;busy(false);resetAnalysis()}catch(e){setBadge(ui.captureBadge,'Capture failed','bad');ui.captureMessage.textContent=e.name==='AbortError'?'Capture timed out. Check Wi-Fi and retry.':e.message;busy(false)}finally{clearTimeout(timer);setTimeout(startStream,180)}}
    function backendBase(){return ui.backendUrl.value.trim().replace(/\/+$/,'')}
    function postDeviceStatus(payload){try{fetch('/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),keepalive:true}).catch(()=>{})}catch(_){}}
    function topSeverity(defects){if(!defects||!defects.length)return '';const rank={low:1,medium:2,high:3};let best='';defects.forEach(d=>{if(!best||(rank[d.severity]||0)>(rank[best]||0))best=d.severity});return best}
    async function checkBackend(){const base=backendBase();if(!/^https?:\/\//i.test(base)){setBackend(false,'Enter a complete http:// URL.');return false}const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),4000);try{const r=await fetch(`${base}/health`,{cache:'no-store',signal:ctrl.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);app.backend=await r.json();const ready=app.backend.ok;setBackend(ready,ready?`${label(app.backend.mode)} mode · ${app.backend.model}`:'API key not configured');return ready}catch(e){app.backend=null;setBackend(false,e.name==='AbortError'?'Backend check timed out.':'Backend is not reachable.');return false}finally{clearTimeout(timer)}}
    function setBackend(ok,message){$('backendTop').textContent=ok?'online':'offline';$('backendTop').style.color=ok?'var(--sage-ink)':'var(--rose-ink)';$('healthBackend').textContent=app.backend?label(app.backend.mode):'Offline';ui.backendMessage.textContent=message}
    function toneFor(status){return status==='no_visible_defect'?'good':status==='defect_suspected'||status==='uncertain'?'warn':status==='retake_required'?'bad':''}
    function makeSvg(name,attrs={}){const el=document.createElementNS(SVG,name);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);return el}
    function selectDefect(index){app.selected=index;[...ui.defectList.children].forEach((el,i)=>el.classList.toggle('selected',i===index));[...ui.overlay.children].forEach((el,i)=>el.classList.toggle('selected',i===index))}
    function renderBoxes(defects){ui.overlay.replaceChildren();defects.forEach((d,i)=>{const b=d.bounding_box,g=makeSvg('g',{class:`bbox ${d.severity}`,'aria-label':`${i+1}. ${label(d.type)}`}),rect=makeSvg('rect',{x:b.x_min,y:b.y_min,width:Math.max(1,b.x_max-b.x_min),height:Math.max(1,b.y_max-b.y_min),rx:10}),tagWidth=Math.max(190,label(d.type).length*21+78),tag=makeSvg('rect',{class:'tag',x:b.x_min,y:Math.max(0,b.y_min-54),width:tagWidth,height:54,rx:8}),text=makeSvg('text',{x:b.x_min+16,y:Math.max(38,b.y_min-16)});text.textContent=`${i+1} · ${label(d.type)}`;g.append(rect,tag,text);g.addEventListener('click',()=>selectDefect(i));ui.overlay.append(g)});const show=defects.length>0;ui.overlay.toggleAttribute('hidden',!show||!ui.overlayToggle.checked);ui.approxNote.hidden=!show;ui.overlayToggle.disabled=!show;ui.annotatedButton.hidden=!show;if(show)selectDefect(0)}
    function showResult(result){app.result=result;ui.analysisEmpty.hidden=true;ui.analysisResult.hidden=false;ui.analyzeButton.hidden=true;setBadge(ui.analysisBadge,'Analysis complete','good');setBadge(ui.resultStatus,label(result.status),toneFor(result.status));setBadge(ui.qualityStatus,`${label(result.image_quality)} image`,result.image_quality==='acceptable'?'good':'warn');ui.resultTitle.textContent=result.status==='defect_suspected'?'Visible regions need review':result.status==='no_visible_defect'?'No visible anomaly found':result.status==='retake_required'?'Retake recommended':'Inspection uncertain';ui.resultSummary.textContent=result.summary;ui.defectList.replaceChildren();result.defects.forEach((d,i)=>{const button=document.createElement('button');button.type='button';button.className='defect';const top=document.createElement('div');top.className='defect-top';const name=document.createElement('span');name.textContent=`${i+1}. ${label(d.type)}`;const meta=document.createElement('span');meta.textContent=`${label(d.severity)} · ${label(d.confidence)}`;const description=document.createElement('p');description.textContent=d.description;top.append(name,meta);button.append(top,description);button.addEventListener('click',()=>selectDefect(i));ui.defectList.append(button)});if(!result.defects.length){const empty=document.createElement('p');empty.textContent='No regions were marked.';ui.defectList.append(empty)}renderBoxes(result.defects);$('analysisTiming').textContent=result.meta?`${result.meta.latency_ms} ms · ${label(result.meta.mode)}`:''}
    async function analyzeCapture(){if(!app.stillBlob)return;busy(true);ui.analysisEmpty.hidden=false;ui.analysisResult.hidden=true;ui.analyzeButton.disabled=true;setBadge(ui.analysisBadge,'Analyzing','warn');$('analysisTitle').textContent='Inspecting visible detail';$('analysisPrompt').textContent='The high-resolution image is being screened. This may take a moment…';postDeviceStatus({state:'analyzing'});const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),90000);try{const r=await fetch(`${backendBase()}/analyze`,{method:'POST',headers:{'Content-Type':'image/jpeg'},body:app.stillBlob,signal:ctrl.signal});let data={};try{data=await r.json()}catch(_){throw new Error('The backend returned an unreadable response.')}if(!r.ok)throw new Error(data.error?.message||`Analysis failed with HTTP ${r.status}`);showResult(data);postDeviceStatus({state:'result',status:data.status,defects:(data.defects||[]).length,severity:topSeverity(data.defects)})}catch(e){postDeviceStatus({state:'error',message:e.name==='AbortError'?'ANALYSIS TIMEOUT':'BACKEND ERROR'});ui.analysisResult.hidden=true;ui.analysisEmpty.hidden=false;setBadge(ui.analysisBadge,e.name==='AbortError'?'Timed out':'Analysis unavailable','bad');$('analysisTitle').textContent=e.name==='AbortError'?'Analysis timed out':'Could not complete analysis';$('analysisPrompt').textContent=e.name==='AbortError'?'The capture is safe. Retry when the connection is stable.':e.message;ui.analyzeButton.hidden=false;ui.analyzeButton.textContent='Retry analysis';ui.analyzeButton.disabled=false}finally{clearTimeout(timer);app.busy=false;ui.captureButton.disabled=false;ui.retakeButton.disabled=false}}
    async function downloadAnnotated(){if(!app.result||!app.stillBlob)return;const canvas=document.createElement('canvas');canvas.width=CAPTURE_WIDTH;canvas.height=CAPTURE_HEIGHT;const ctx=canvas.getContext('2d');ctx.drawImage(ui.still,0,0);ctx.lineWidth=8;ctx.font='650 30px Avenir Next, sans-serif';app.result.defects.forEach((d,i)=>{const b=d.bounding_box,color=d.severity==='high'?'#c5535f':d.severity==='low'?'#557fc4':'#d58b35';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.strokeRect(b.x_min,b.y_min,b.x_max-b.x_min,b.y_max-b.y_min);const text=`${i+1} · ${label(d.type)}`,w=ctx.measureText(text).width+28,y=Math.max(0,b.y_min-48);ctx.fillRect(b.x_min,y,w,48);ctx.fillStyle='#fff';ctx.fillText(text,b.x_min+14,y+34)});canvas.toBlob(blob=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`solar-inspection-annotated-${Date.now()}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/jpeg',.92)}
    async function refreshHealth(){try{const r=await fetch(`/health?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json(),online=d.camera&&d.wifi;setBadge($('deviceBadge'),online?'Camera online':'Camera unavailable',online?'good':'bad');$('topRssi').textContent=`${d.rssi} dBm`;$('topFps').textContent=d.stream_fps.toFixed(1);$('frameFps').textContent=`${d.stream_fps.toFixed(1)} fps`;$('metricFps').textContent=`${d.stream_fps.toFixed(1)} fps`;$('healthRssi').textContent=`${d.rssi} dBm`;$('healthHeap').textContent=formatBytes(d.free_heap);$('healthPsram').textContent=formatBytes(d.free_psram);$('healthIp').textContent=d.ip;$('healthFirmware').textContent=d.firmware||'—'}catch(_){setBadge($('deviceBadge'),'Camera unavailable','bad')}}
    ui.captureButton.addEventListener('click',captureImage);ui.retakeButton.addEventListener('click',captureImage);ui.analyzeButton.addEventListener('click',analyzeCapture);ui.annotatedButton.addEventListener('click',downloadAnnotated);ui.overlayToggle.addEventListener('change',()=>ui.overlay.toggleAttribute('hidden',!ui.overlayToggle.checked));$('backendSave').addEventListener('click',()=>{localStorage.setItem('solarBackendUrl',backendBase());checkBackend()});$('refreshButton').addEventListener('click',()=>{refreshHealth();checkBackend()});ui.downloadButton.addEventListener('click',e=>{if(!app.stillUrl)e.preventDefault()});
    startStream();refreshHealth();checkBackend();setInterval(refreshHealth,5000);setInterval(checkBackend,20000);
  </script>
</body>
</html>
)HTML";
